### ISSUE TITLE
Can you release the evaluation code or more details about evaluation?

### ISSUE THREAD

**Issue by Tomwmg** [MichiganCOG/Video-Grounding-from-Text#2]

**Comment by LuoweiZhou** [comment]
Hi @Tomwmg, thank you for your interest in our work. We are working the releases and will inform you once they are ready (likely next week). Please stay tuned.

**Comment by LuoweiZhou** [comment]
The repo is updated, including the evaluation code. We will release the separate (offline) evaluation script and server by this month. Thank you for your patience!

**Comment by Tomwmg** [comment]
Thank you very much!
