### ISSUE TITLE
No such file or directory: './data/yc2/roi_box\\validation-box-100.pth'

### ISSUE THREAD

**Issue by Tomwmg** [MichiganCOG/Video-Grounding-from-Text#3]
When I run the test.py this error happened,just 'validation-box-100.txt' in './data/yc2/roi_box',not exist 'validation-box-100'.pth'.

**Comment by LuoweiZhou** [comment]
Hi @Tomwmg, you can download region features from here: https://github.com/MichiganCOG/Video-Grounding-from-Text#data-preparation

**Comment by Tomwmg** [comment]
Thank you!
