### ISSUE TITLE
Could you release  the sentence anotation of testing set?

### ISSUE THREAD

**Issue by Xun-Yang** [MichiganCOG/Video-Grounding-from-Text#5]
Hi 
 I know the bbx annotations of testing set is only for online evaluation. However, the sentence annotations of testing set do not affect the online evaluation. I didn't find them in the released testing split. 

Could you release  the sentence annotations of testing set? They are useful in our model.

Thanks.

**Comment by LuoweiZhou** [comment]
@Xun-Yang we do not plan to release the testing sentences/segments for dense video captioning [evaluation](https://competitions.codalab.org/competitions/21492) purposes. We'd suggest you report the grounding results on the validation set for now and email me (luozhou@umich.edu) and Nathan (natlouis@umich.edu) with your model/docker/instructions on how to run your code so we can run it on our test set.
