### ISSUE TITLE
Could you provide the missing_videos?

### ISSUE THREAD

**Issue by Tomwmg** [MichiganCOG/Video-Grounding-from-Text#6]
Sorry to bother you. When I use the download_youcookii_videos.py to download the videos, there are some invalid videos, could you provide the missing_videos?The attach is missing videos list. [missing_videos.txt](https://github.com/MichiganCOG/Video-Grounding-from-Text/files/3371512/missing_videos.txt)

**Comment by natlouis** [comment]
Yes, please send me an email with the list and I’ll share a link with you to download your missing videos.

Email me at: natlouis@umich.edu

**Comment by natlouis** [comment]
We have now made all raw video files available for download for non-commercial, research purposes only. They can be found on the YouCook2 [Downloads](http://youcook2.eecs.umich.edu/download) page.
